pull_request_rules:
  - name: Automerge approved PRs
    conditions:
      - base=main
      - approved-reviews-by=radosnystudent
      - status-success=build
      - status-success=test (ubuntu-latest, 3.11)
      - status-success=test (ubuntu-latest, 3.12)
      - status-success=test (ubuntu-latest, 3.13)
      - status-success=test (windows-latest, 3.11)
      - status-success=test (windows-latest, 3.12)
      - status-success=test (windows-latest, 3.13)
      - status-success=test (macos-latest, 3.11)
      - status-success=test (macos-latest, 3.12)
      - status-success=test (macos-latest, 3.13)
      - -conflict
    actions:
      merge:
        method: rebase

  - name: Notify author about conflicts
    conditions:
      - base=main
      - conflict
    actions:
      comment:
        message: "@{{author}} Your PR is in conflict and cannot be merged."
