name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Format check with Black
        run: black --check .

      - name: Lint with Ruff
        run: ruff check .

      - name: Type check with Mypy
        run: mypy .

      - name: Security check with Bandit
        run: bandit -r . -ll -x launcher.py

      - name: Install Qt dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-xinerama0

      # Start MongoDB service for Linux (using container action)
      - name: Start MongoDB (Linux)
        if: runner.os == 'Linux'
        uses: supercharge/mongodb-github-action@v1
        with:
          mongodb-version: "6.0"

      # Start MongoDB for macOS using Homebrew
      - name: Start MongoDB (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew tap mongodb/brew
          brew install mongodb-community@6.0
          brew services start mongodb-community@6.0

      # Start MongoDB for Windows using zip archive (run mongod in foreground and wait for port)
      - name: Start MongoDB (Windows)
        if: runner.os == 'Windows'
        run: |
          $mongoVersion = '6.0.5'
          $mongoUrl = "https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-$mongoVersion.zip"
          Invoke-WebRequest -Uri $mongoUrl -OutFile mongo.zip
          $extractPath = "$PWD\mongodb"
          Expand-Archive -Path mongo.zip -DestinationPath $extractPath
          $mongoDir = Get-ChildItem -Directory -Path $extractPath -Recurse | Where-Object { $_.Name -like "mongodb-win32-x86_64-windows-*" } | Select-Object -First 1
          if (-not $mongoDir) { Write-Error 'MongoDB directory not found after extraction.'; exit 1 }
          $mongoBin = Join-Path $mongoDir.FullName 'bin'
          $mongod = Join-Path $mongoBin 'mongod.exe'
          if (-not (Test-Path $mongod)) { Write-Error "mongod.exe not found at $mongod"; exit 1 }
          $env:PATH += ";$mongoBin"
          New-Item -ItemType Directory -Force -Path C:\data\db | Out-Null
          New-Item -ItemType Directory -Force -Path C:\data\log | Out-Null
          Start-Process -NoNewWindow -FilePath $mongod -ArgumentList "--dbpath=C:\data\db --logpath=C:\data\log\mongod.log --logappend --bind_ip=127.0.0.1" -WindowStyle Hidden
          $maxWait = 30
          $waited = 0
          while ($waited -lt $maxWait) {
            try {
              $tcp = New-Object System.Net.Sockets.TcpClient
              $tcp.Connect('localhost', 27017)
              $tcp.Close()
              Write-Host 'MongoDB is up!'
              break
            } catch {
              Start-Sleep -Seconds 1
              $waited++
            }
          }
          if ($waited -eq $maxWait) { Write-Error 'MongoDB did not start in time.'; exit 1 }
        shell: pwsh

      - name: Test with pytest
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            export QT_QPA_PLATFORM=offscreen
            xvfb-run -a pytest --cov=. --cov-report=xml
          else
            pytest --cov=. --cov-report=xml
          fi
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
